# Generated by Django 3.1.5 on 2021-01-15 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Note_Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default=False, max_length=40, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('password_required', models.BooleanField(default=False)),
                ('add_to_fav', models.BooleanField(default=False)),
                ('colour_of_notes', models.CharField(choices=[('red', 'RED'), ('green', 'GREEN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('blue', 'BLUE'), ('white', 'WHITE')], default='white', max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, to='notes.category', verbose_name='Category')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
